hydra:
  run:
    dir: ${log_dir}/${now:%Y%m%d}/${now:%H%M%S}_${logmbh_line}_${model_name}

# Directories
data_dir: '../reproducible_output'
catalogue_dir: '${data_dir}/catalogue'
spectra_dir: '${data_dir}/spectra'
log_dir: '${data_dir}/logs'
# Catalogue files
catalogue_file: 'dr16q_prop_Oct23_2022.fits.gz'
filteredcatalogue_file: 'sdssdr16q_prop.csv'

# Experiment
model_name: 'DenseEncoder'
logmbh_line: 'LOGMBH_HB' # 'LOGMBH_HB', 'LOGMBH_MGII'
seed: 42

# Train setup
num_workers: 1
batch_size: 64
frac_test_size: 0.3
max_epochs: 100
